services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=devdb'
      - 'POSTGRES_PASSWORD=securepassword'
      - 'POSTGRES_USER=devuser'
    ports:
      - '5432:5432'
  user-service:
    image: 'user-service:0.0.1-SNAPSHOT'
    ports:
      - '9898:9898'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgres:5432/devdb'
      - 'DATABASE_USER=devuser'
      - 'DATABASE_PASSWORD=securepassword'
      - 'PORT=9898'
    depends_on:
        - postgres
  todo-service:
    image: 'todo-service:0.0.1-SNAPSHOT'
    ports:
      - '9899:9899'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgres:5432/devdb'
      - 'DATABASE_USER=devuser'
      - 'DATABASE_PASSWORD=securepassword'
      - 'PORT=9899'
    depends_on:
        - postgres
