spring:
  application:
    name: todo-service
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: securepassword
    driver-class-name: org.postgresql.Driver
server:
    port: 9091