spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devdb}
    username: ${DATABASE_USER:devuser}
    password: ${DATABASE_PASSWORD:securepassword}
    driver-class-name: org.postgresql.Driver
server:
  port: ${PORT:9091}