apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deployment
  labels:
    app: todo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service-deployment
  template:
    metadata:
      name: todo-service-deployment
      labels:
        app: todo-service-deployment
    spec:
      containers:
        - name: todo-service-deployment
          image: todo-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
      