spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          - id: todo-service
            uri: lb://todo-service
            predicates:
              - Path=/api/todos/**
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
